CREATE DATABASE wildlife_tracker;

\c wildlife_tracker;

CREATE TABLE animals(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    animalName VARCHAR,
    animalType VARCHAR,
    health VARCHAR,
    age VARCHAR
);

CREATE TABLE sightings (
    id serial PRIMARY KEY,
    animal_id int,
    location varchar,
    ranger varchar,
    timestamp timestamp);
